# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843c1a65f06edb7ba2b6fdf972fc832abe833bf865649f4635a69969c7e423c70d246992ea8858d4c3d4f1050f1efacd65a25f458d6299ebfc9ff47399cb14d2

test:
  secret_key_base: 72cc37aaaae376cbaa3da352d46d3e12437396b6af49b28eac782b5f14277e6eeb1653622f123068b34bd56734c6990dc5f4f9eb34fc83430ff85ffcd1a0b66f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
